//
//  MovieSearchPresenter.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 10/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieSearchPresentationLogic
{
    func presentMatchingMovies(movies: [MovieResultResponseModel])
    func onGetMatchingMoviesFailed()
}

class MovieSearchPresenter: MovieSearchPresentationLogic
{
    
    weak var viewController: MovieSearchDisplayLogic?
    
    func presentMatchingMovies(movies: [MovieResultResponseModel]) {
        
        
        //parse previously to viewmodel.... before cell
        let movieCollectionCells: [CollectionDrawerItemProtocol] = movies.map({MovieCollectionViewCellModel.init(movieResponseModel: $0)})
        viewController?.showResultMovies(movies: movieCollectionCells)
        
    }
    
    func onGetMatchingMoviesFailed() {
        
    }
}
