//
//  MovieSearchViewController.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 10/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieSearchDisplayLogic: class, BaseViewDisplayLogic
{
    func showResultMovies(viewModel: MovieSearchViewModel)
    func showNoMoviesFoundOrError(viewModel: MovieSearchViewModel)
}

class MovieSearchViewController: BaseViewController
{
    var interactor: MovieSearchBusinessLogic?
    var router: (NSObjectProtocol & MovieSearchRoutingLogic & MovieSearchDataPassing)?
    
    private var resultMovieCells: [CollectionDrawerItemProtocol] = []
    var selectedIndex: Int = 0
    private let verticalInset: CGFloat = 20
    private let horizontalInset: CGFloat = 40
    

    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setupViews()
        setupConstraints()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.setNavigationBarHidden(true, animated: true)
    }
    
    // MARK: Views
    
    let searchBar: UISearchBar = {
        let bar = UISearchBar.init()
        bar.barStyle = .black
        bar.searchBarStyle = .minimal
        bar.placeholder = Constants.Search.searchBarPlaceholder
        return bar
    }()
    
    let resultsCollectionView: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .vertical
        layout.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
        let collectionView = UICollectionView.init(frame: CGRect.init(), collectionViewLayout: layout)
        collectionView.backgroundColor = .clear
        collectionView.keyboardDismissMode = .onDrag
        collectionView.indicatorStyle = .white
        collectionView.showsVerticalScrollIndicator = true
        collectionView.contentInset = UIEdgeInsets.init(top: 10, left: 20, bottom: 10, right: 20)
        return collectionView
    }()
    
    private func setupViews(){
        self.view.addSubview(searchBar)
        self.view.addSubview(resultsCollectionView)
        searchBar.delegate = self
        resultsCollectionView.delegate = self
        resultsCollectionView.dataSource = self
    }
    
    private func setupConstraints(){
        searchBar.snp.makeConstraints { (make) in
            make.top.left.right.equalTo(self.view.safeAreaLayoutGuide)
        }
        
        resultsCollectionView.snp.makeConstraints { (make) in
            make.top.equalTo(searchBar.snp.bottom)
            make.left.right.bottom.equalTo(self.view.safeAreaLayoutGuide)
        }
    }
    
    private func updateResultCells(newResults: [CollectionDrawerItemProtocol]){
        self.resultMovieCells = newResults
        resultsCollectionView.reloadData()
    }
    
    private func isEmptyStateCell(indexPath: IndexPath) -> Bool {
        resultMovieCells[indexPath.row] is EmptyStateCollectionCellModel
    }
    
}

//MARK: -CollectionView management

extension MovieSearchViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cellModel = resultMovieCells[indexPath.row]
        let drawer = cellModel.collectionDrawer
        let cell = drawer.dequeueCollectionCell(collectionView, indexPath: indexPath)
        drawer.drawCollectionCell(cell, withItem: cellModel)
        return cell
    }
    
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        resultMovieCells.count
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if !isEmptyStateCell(indexPath: indexPath){
            selectedIndex = indexPath.row
            router?.routeToMovieDetail()
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        if !isEmptyStateCell(indexPath: indexPath){
            return CGSize.init(width: 80, height: 100)
        }else{
            return CGSize.init(width: collectionView.frame.width-horizontalInset, height: collectionView.frame.height-verticalInset)
        }
    }
    
}


//MARK: -SearchBar delegate implementation

extension MovieSearchViewController: UISearchBarDelegate {
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        interactor?.fetchMovies(queryString: searchBar.text ?? "")
        searchBar.resignFirstResponder()
    }
    
    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        updateResultCells(newResults: [])
        searchBar.resignFirstResponder()
    }
    
}

//MARK: -Display logic implementation

extension MovieSearchViewController: MovieSearchDisplayLogic {
    
    func showResultMovies(viewModel: MovieSearchViewModel) {
        updateResultCells(newResults: viewModel.movies)
    }
    
    func showNoMoviesFoundOrError(viewModel: MovieSearchViewModel){
        updateResultCells(newResults: viewModel.movies)
    }
    
}
