//
//  MovieSearchInteractor.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 10/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieSearchBusinessLogic
{
  //func doSomething(request: MovieSearch.Something.Request)
}

protocol MovieSearchDataStore
{
  //var name: String { get set }
}

class MovieSearchInteractor: MovieSearchBusinessLogic, MovieSearchDataStore
{
  var presenter: MovieSearchPresentationLogic?
  var worker: MovieSearchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: MovieSearch.Something.Request)
//  {
//    worker = MovieSearchWorker()
//    worker?.doSomeWork()
//    
//    let response = MovieSearch.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
}
