//
//  MovieSearchPresenter.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 10/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieSearchPresentationLogic
{
  //func presentSomething(response: MovieSearch.Something.Response)
}

class MovieSearchPresenter: MovieSearchPresentationLogic
{
  weak var viewController: MovieSearchDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: MovieSearch.Something.Response)
//  {
//    let viewModel = MovieSearch.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
