//
//  MovieDetailViewControllerTests.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import VIP_demo
import XCTest

class MovieDetailViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MovieDetailViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupMovieDetailViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMovieDetailViewController()
  {
    sut = MovieDetailViewController()
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class MovieDetailBusinessLogicSpy: MovieDetailBusinessLogic
  {
    var movieDetailCalled = false

    func fetchMovieDetail() {
        movieDetailCalled = true
    }
 
  }
  
  // MARK: Tests
  
  func testShouldFetchMovieDetailsWhenLoaded()
  {
    // Given
    let spy = MovieDetailBusinessLogicSpy()
    sut.interactor = spy
    
    // When
    loadView()
    
    // Then
    XCTAssertTrue(spy.movieDetailCalled, "viewDidLoad() should ask the interactor to fetch the movie detail")
  }
  
  func testMovieTitle()
  {
    // Given
    let movieInfoVM = MovieInfoViewModel.init(title: "titulo", detailImgUrl: "", overview: "", productionCompanies: [], releaseDate: "", tagLine: "", voteAverage: "")
    
    let viewModel = MovieDetailViewModel.init(movieInfoVM: movieInfoVM, movieDetailCells: [])

    // When
    loadView()
    
    sut.displayMovieInfo(viewModel: viewModel)
    
    // Then
    XCTAssertEqual(sut.title, viewModel.movieInfoVM.title, "displayMovieInfo(viewModel:) should update the viewcontroller's title with the movie title")
  }

}
