//
//  MovieDetailWorkerTests.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//
//@testable import VIP_demo
//import XCTest
//
//class MovieDetailWorkerTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: MovieDetailWorker!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupMovieDetailWorker()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupMovieDetailWorker()
//  {
//    sut = MovieDetailWorker()
//  }
//  
//  // MARK: Test doubles
//  
//  // MARK: Tests
//  
//  func testSomething()
//  {
//    // Given
//    
//    // When
//    
//    // Then
//  }
//}
