//
//  MovieDetailPresenterTests.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//@testable import VIP_demo
//import XCTest
//
//class MovieDetailPresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: MovieDetailPresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupMovieDetailPresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupMovieDetailPresenter()
//  {
//    sut = MovieDetailPresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class MovieDetailDisplayLogicSpy: MovieDetailDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: MovieDetail.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = MovieDetailDisplayLogicSpy()
//    sut.viewController = spy
//    let response = MovieDetail.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
