# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VIP_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VIP_demo
 
  pod 'Alamofire'

  target 'VIP_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VIP_demoUITests' do
    # Pods for testing
  end

end
