//
//  MovieSearchPresenterTests.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import VIP_demo
import XCTest
//
//class MovieSearchPresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: MovieSearchPresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupMovieSearchPresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupMovieSearchPresenter()
//  {
//    sut = MovieSearchPresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class MovieSearchDisplayLogicSpy: MovieSearchDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: MovieSearch.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = MovieSearchDisplayLogicSpy()
//    sut.viewController = spy
//    let response = MovieSearch.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
