//
//  MovieSearchInteractorTests.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 13/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import VIP_demo
import XCTest

//class MovieSearchInteractorTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: MovieSearchInteractor!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupMovieSearchInteractor()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupMovieSearchInteractor()
//  {
//    sut = MovieSearchInteractor()
//  }
//  
//  // MARK: Test doubles
//  
//  class MovieSearchPresentationLogicSpy: MovieSearchPresentationLogic
//  {
//    var presentSomethingCalled = false
//    
//    func presentSomething(response: MovieSearch.Something.Response)
//    {
//      presentSomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testDoSomething()
//  {
//    // Given
//    let spy = MovieSearchPresentationLogicSpy()
//    sut.presenter = spy
//    let request = MovieSearch.Something.Request()
//    
//    // When
//    sut.doSomething(request: request)
//    
//    // Then
//    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
//  }
//}
