//
//  HomeViewControllerTests.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 05/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import VIP_demo
import XCTest

class HomeViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: HomeViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupHomeViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupHomeViewController()
  {
    sut = HomeViewController()
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class HomeBusinessLogicSpy: HomeBusinessLogic
  {
    var fetchMoviesOnLoadCalled = false
    
    func fetchMovies() {
        fetchMoviesOnLoadCalled = true
    }
    
  }
  
  // MARK: Tests
  
  func testShouldFetchMoviesWhenIsLoaded()
  {
    // Given
    let spy = HomeBusinessLogicSpy()
    sut.interactor = spy
    
    // When
    loadView()
    
    // Then
    XCTAssertTrue(spy.fetchMoviesOnLoadCalled, "viewDidLoad() should ask the interactor to fetch movies categories")
  }
  
  func testDisplayCategoryCells()
  {
    // Given
    let viewModel = HomeViewModel.init(movieCategories: [MovieCategoryCellModel.init(title: "Testing", elementsToDisplay: [])])
    
    // When
    loadView()
    sut.loadCategoriesAndMovies(viewModel: viewModel)
    
    // Then
    

    
    XCTAssertEqual(viewModel.movieCategories.count, sut.tableView.numberOfRows(inSection: 0), "loadCategoriesAndMovies should reload the tableView with the same number of category downloaded that are not empty")
  }
}
