//
//  HomeInteractorTests.swift
//  VIP_demo
//
//  Created by Borja Saez de Guinoa Vilaplana on 05/01/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import VIP_demo
import XCTest

//class HomeInteractorTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: HomeInteractor!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupHomeInteractor()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupHomeInteractor()
//  {
//    sut = HomeInteractor()
//  }
//  
//  // MARK: Test doubles
//  
//  class HomePresentationLogicSpy: HomePresentationLogic
//  {
//    
//    func onGetMoviesForHomeSucceed(popular: [MovieResultResponseModel], topRated: [MovieResultResponseModel], nowPlaying: [MovieResultResponseModel]) {
//        
//    }
//    
//    func onGetMoviesForHomeAllFailed() {
//        
//    }
//        
//  }
//  
//  // MARK: Tests
//  
//  func testDoSomething()
//  {
//    // Given
//    let spy = HomePresentationLogicSpy()
//    sut.presenter = spy
//    
//    // When
//    sut.fetchMovies()
//    
//    // Then
//    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
//  }
//}
